name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rust-src
        
    - name: Build ARM7 BIOS
      working-directory: ./rust/ndsbiosa7
      run: cargo build
      
    - name: Archive debug ARM7 BIOS
      uses: actions/upload-artifact@v3
      with:
        name: arm7bios
        path: |
          ./rust/ndsbiosa7/target/armv4t-none-eabi/debug/*.rlib
